### ISSUE TITLE
No colors in xfce-panel bg and fg

### ISSUE THREAD

**Issue by gps08** [B00merang-Project/Chrome-OS#15]
All colors are not defined in the gtk2 theme for xfce panel

**Comment by Elbullazul** [comment]
@gps08 Xfce is currently moving between GTK 2 and 3 and it's hard to keep up since Debian uses an old version of Xfce and Arch uses the newest. In between there must be 4 or 5 versions each with a different stage of progress in the migration. I can't support Xfce at the moment, I am not using it and it's a moving target (for now). When they get stable on their migration I will address this issue.

**Comment by gps08** [comment]
can i do some xfce-panel work for you  to merge?

**Comment by Elbullazul** [comment]
@gps08 shure, I can set up a new branch

**Comment by gps08** [comment]
@Elbullazul  okay thanks

**Comment by Elbullazul** [comment]
seems we've hit a snag: [#16](https://github.com/B00merang-Project/B00merang-Themes/issues/16)

will merge changes made to B00merang Themes if I find and correct the bug

**Comment by Elbullazul** [comment]
merged b64362a
